version: "3.7"

services:
  payd:
    container_name: payd
    image: local.payd
    environment:
      DB_DSN: "file:data/wallet.db?cache=shared&_foreign_keys=true;"
      DB_SCHEMA_PATH: "migrations"
    volumes:
      - ~/data/payd:/data
    ports:
      - "8443:8443"
    networks:
      - platform-services-network

networks:
  platform-services-network:
    external: true
    name: platform-services-network